site_name: "Java FS Notes"
site_description: "Comprehensive Java Full Stack interview-preparation notes (Spring Boot + Angular)"
site_author: "Ramakrishna Sangamreddy"
site_url: "https://sramakrishnaa.github.io/java-fullstack-notes/"

repo_url: "https://github.com/sramakrishnaa/java-fullstack-notes"
repo_name: "sramakrishnaa/java-fullstack-notes"
edit_uri: "edit/main/docs/"

use_directory_urls: false
strict: true

theme:
  name: material
  language: en
  font: false

  icon:
    logo: material/layers-triple
    repo: material/git
    edit: material/pencil
    view: material/eye
  favicon: assets/images/layers-triple.svg

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    # Navigation
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer

    # TOC
    - toc.follow

    # Search
    - search.suggest
    - search.highlight
    - search.share

    # Content
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tabs.link

plugins:
  - search:
      lang: en
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      
  - tags

  - minify:
      minify_html: true

  - awesome-pages:
      collapse_single_pages: false
      strict: false

  - glightbox

  # - panzoom:
  #     mermaid: true
  #     images: true
  #     key: "alt"
  #     always_show_hint: false


markdown_extensions:
  - admonition
  - tables
  - def_list

  - toc:
      permalink: true
      permalink_title: Anchor link to this section
      toc_depth: 3
      title: "On this page"

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.caret

  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.tasklist:
      custom_checkbox: true



extra:
  social:
    - icon: material/github
      link: https://github.com/sramakrishnaa
      name: GitHub Profile

    - icon: material/linkedin
      link: https://linkedin.com/in/sramakrishnaa
      name: LinkedIn Profile

copyright: Copyright © 2026 sramakrishnaa